"use client";
import { useState, useEffect, Suspense } from "react";
import { useSearchParams } from "next/navigation";
import { CheckCircle, AlertCircle, Loader2, Dumbbell, QrCode } from "lucide-react";

const BASE_URL =
  process.env.NEXT_PUBLIC_API_URL ||
  "https://fitzone-backend-vis3.onrender.com/api";

// ─────────────────────────────────────────────────────────────────
// CheckinPage — Member's Personal QR Scan Flow
//
// WORKFLOW:
//   1. Gym Owner gives each member their personal QR code
//      (generated by qrService → encodes { memberId, qrId, type })
//
//   2. Member scans QR with phone camera
//      → Two possible URL patterns:
//
//      A) QR encodes a URL:
//         https://gym-fit-zone.vercel.app/checkin?qrData=<encoded-json>
//         → Page reads qrData from URL, auto-submits to backend
//
//      B) QR encodes raw JSON directly (qrService default):
//         { "memberId": "...", "qrId": "...", "type": "member-checkin" }
//         → Phone camera opens the JSON as text, user pastes or
//           gym uses a scanner device that sends to this page
//
//   3. Backend: qrId → find member → verify Active → mark attendance
//   4. Show success / error — NO phone entry needed
// ─────────────────────────────────────────────────────────────────

function CheckinContent() {
  const params = useSearchParams();

  // URL params — gym owner QR encodes these
  const qrDataParam  = params.get("qrData")   || "";   // full JSON string encoded in URL
  const qrIdParam    = params.get("qrId")     || "";   // direct qrId in URL
  const memberIdParam = params.get("memberId") || "";  // direct memberId in URL
  const gymName      = decodeURIComponent(params.get("name") || "Your Gym");

  const [status,  setStatus]  = useState("idle");   // idle | loading | success | error | already
  const [message, setMessage] = useState("");
  const [member,  setMember]  = useState(null);

  // ── Auto-submit as soon as we have QR data in URL ──────────────
  useEffect(() => {
    const hasData = qrDataParam || qrIdParam || memberIdParam;
    if (hasData) {
      submitCheckin({ qrData: qrDataParam || undefined, qrId: qrIdParam || undefined, memberId: memberIdParam || undefined });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const submitCheckin = async ({ qrData, qrId, memberId }) => {
    setStatus("loading");
    setMessage("");

    // Build body — send whatever we have
    const body = {};
    if (qrData)    body.qrData   = qrData;
    if (qrId)      body.qrId     = qrId;
    if (memberId)  body.memberId = memberId;

    try {
      const res  = await fetch(`${BASE_URL}/attendance/qr-checkin`, {
        method:  "POST",
        headers: { "Content-Type": "application/json" },
        body:    JSON.stringify(body),
      });
      const data = await res.json();

      if (!res.ok) {
        setStatus("error");
        setMessage(data.message || "Check-in failed. Please try again.");
      } else if (data.alreadyIn) {
        setStatus("already");
        setMessage(data.message);
        setMember(data.member);
      } else {
        setStatus("success");
        setMessage(data.message);
        setMember(data.member);
      }
    } catch {
      setStatus("error");
      setMessage("Network error. Please check your connection and try again.");
    }
  };

  // ── Loading ────────────────────────────────────────────────────
  if (status === "loading") {
    return (
      <div className="min-h-screen bg-gradient-to-br from-blue-600 to-indigo-700 flex items-center justify-center p-4">
        <div className="bg-white rounded-3xl shadow-2xl w-full max-w-sm p-10 text-center">
          <div className="w-20 h-20 rounded-full bg-blue-100 flex items-center justify-center mx-auto mb-5">
            <Loader2 size={40} className="text-blue-600 animate-spin" />
          </div>
          <h1 className="text-xl font-black text-gray-800 mb-2">Verifying...</h1>
          <p className="text-sm text-gray-500">Checking your membership</p>
        </div>
      </div>
    );
  }

  // ── Success ────────────────────────────────────────────────────
  if (status === "success") {
    return (
      <div className="min-h-screen bg-gradient-to-br from-emerald-50 to-teal-100 flex items-center justify-center p-4">
        <div className="bg-white rounded-3xl shadow-2xl w-full max-w-sm p-8 text-center">
          <div className="w-20 h-20 rounded-full bg-emerald-100 flex items-center justify-center mx-auto mb-5">
            <CheckCircle size={40} className="text-emerald-500" />
          </div>
          <h1 className="text-2xl font-black text-gray-800 mb-2">Welcome! ✓</h1>
          <p className="text-lg font-bold text-blue-600 mb-1">{member?.name}</p>
          <p className="text-sm text-gray-500 mb-4">{member?.planName || "Member"}</p>
          <p className="text-sm text-gray-600 bg-gray-50 rounded-xl px-4 py-3">{message}</p>
          <div className="mt-6 flex items-center justify-center gap-2 text-xs text-gray-400">
            <Dumbbell size={14} className="text-blue-500" />
            <span>FitZone · {gymName}</span>
          </div>
        </div>
      </div>
    );
  }

  // ── Already checked in ─────────────────────────────────────────
  if (status === "already") {
    return (
      <div className="min-h-screen bg-gradient-to-br from-amber-50 to-orange-100 flex items-center justify-center p-4">
        <div className="bg-white rounded-3xl shadow-2xl w-full max-w-sm p-8 text-center">
          <div className="w-20 h-20 rounded-full bg-amber-100 flex items-center justify-center mx-auto mb-5">
            <CheckCircle size={40} className="text-amber-500" />
          </div>
          <h1 className="text-2xl font-black text-gray-800 mb-2">Already Checked In!</h1>
          <p className="text-lg font-bold text-blue-600 mb-1">{member?.name}</p>
          <p className="text-sm text-gray-500 mb-4">{member?.planName || "Member"}</p>
          <p className="text-sm text-gray-600 bg-gray-50 rounded-xl px-4 py-3">{message}</p>
          <div className="mt-6 flex items-center justify-center gap-2 text-xs text-gray-400">
            <Dumbbell size={14} className="text-blue-500" />
            <span>FitZone · {gymName}</span>
          </div>
        </div>
      </div>
    );
  }

  // ── Error ──────────────────────────────────────────────────────
  if (status === "error") {
    return (
      <div className="min-h-screen bg-gradient-to-br from-red-50 to-rose-100 flex items-center justify-center p-4">
        <div className="bg-white rounded-3xl shadow-2xl w-full max-w-sm p-8 text-center">
          <div className="w-20 h-20 rounded-full bg-red-100 flex items-center justify-center mx-auto mb-5">
            <AlertCircle size={40} className="text-red-500" />
          </div>
          <h1 className="text-xl font-black text-gray-800 mb-2">Check-in Failed</h1>
          <p className="text-sm text-red-600 bg-red-50 rounded-xl px-4 py-3">{message}</p>
          <div className="mt-6 flex items-center justify-center gap-2 text-xs text-gray-400">
            <Dumbbell size={14} className="text-blue-500" />
            <span>FitZone · {gymName}</span>
          </div>
        </div>
      </div>
    );
  }

  // ── Idle — no QR data in URL (direct page visit) ──────────────
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-600 to-indigo-700 flex items-center justify-center p-4">
      <div className="bg-white rounded-3xl shadow-2xl w-full max-w-sm overflow-hidden">
        <div className="bg-gradient-to-r from-blue-600 to-indigo-600 px-6 py-8 text-center">
          <div className="w-16 h-16 bg-white/20 rounded-2xl flex items-center justify-center mx-auto mb-3">
            <QrCode size={32} className="text-white" />
          </div>
          <h1 className="text-xl font-black text-white">FitZone Check-in</h1>
          <p className="text-blue-200 text-sm mt-1">{gymName}</p>
        </div>
        <div className="px-6 py-8 text-center">
          <p className="text-gray-600 text-sm leading-relaxed">
            Please scan your personal QR code using your phone camera to mark attendance automatically.
          </p>
          <p className="text-xs text-gray-400 mt-4">
            Contact your gym if you don't have your QR code.
          </p>
        </div>
      </div>
    </div>
  );
}

// ─────────────────────────────────────────────────────────────────
export default function CheckinPage() {
  return (
    <Suspense
      fallback={
        <div className="min-h-screen bg-gradient-to-br from-blue-600 to-indigo-700 flex items-center justify-center">
          <Loader2 size={40} className="text-white animate-spin" />
        </div>
      }
    >
      <CheckinContent />
    </Suspense>
  );
}
